# Generated by Django 3.2.5 on 2021-08-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condo_name', models.CharField(max_length=64)),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('building_type', models.IntegerField(blank=True, null=True)),
                ('condo_corp', models.CharField(blank=True, max_length=64, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('builder', models.IntegerField(blank=True, null=True)),
                ('architect', models.IntegerField(blank=True, null=True)),
                ('interior_designer', models.IntegerField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('pm', models.IntegerField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=64, null=True)),
                ('view_floor_plans', models.CharField(blank=True, max_length=64)),
                ('modified_date', models.DateTimeField(default=None)),
                ('e_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='Active', max_length=10)),
                ('amenities', models.ManyToManyField(to='condos.Amenity')),
            ],
        ),
        migrations.CreateModel(
            name='CondoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condo_type', models.CharField(blank=True, max_length=64)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('create_by', models.IntegerField(default=None)),
                ('modified_by', models.IntegerField(default=None)),
                ('e_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=18)),
                ('phone_number_canonical', models.CharField(max_length=18)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='condos.condo')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='condos.condo')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='condos.condo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('street_name', models.CharField(blank=True, max_length=64, null=True)),
                ('street_address', models.CharField(blank=True, max_length=64, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=64, null=True)),
                ('e_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='Active', max_length=10)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='condos.condo')),
            ],
        ),
    ]
