# Generated by Django 3.2.5 on 2021-08-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condo_type', models.CharField(blank=True, max_length=64)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('create_by_id', models.IntegerField(default=None)),
                ('modified_by_id', models.IntegerField(default=None)),
                ('e_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(default='ON', max_length=10)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('create_by_id', models.IntegerField(default=None)),
                ('modified_by_id', models.IntegerField(default=None)),
                ('e_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Condos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condo_name', models.CharField(blank=True, max_length=64)),
                ('picture', models.CharField(blank=True, default=None, max_length=500)),
                ('street_name', models.CharField(blank=True, max_length=64)),
                ('street_address', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, default=None, max_length=64)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default=None, max_length=2000)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('amenities', models.CharField(blank=True, default=None, max_length=500)),
                ('building_type_id', models.IntegerField(default=None)),
                ('condo_corp', models.CharField(blank=True, max_length=64)),
                ('floors', models.IntegerField()),
                ('units', models.IntegerField()),
                ('builder_id', models.IntegerField(default=None)),
                ('architect_id', models.IntegerField(default=None)),
                ('interior_designer_id', models.IntegerField(default=None)),
                ('date_completed', models.DateTimeField(default=None)),
                ('pm_id', models.IntegerField(default=None)),
                ('developer', models.CharField(blank=True, default=None, max_length=64)),
                ('send_email', models.CharField(blank=True, default=None, max_length=64)),
                ('view_floor_plans', models.CharField(blank=True, max_length=64)),
                ('created_date', models.DateTimeField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('created_by_id', models.IntegerField(default=None)),
                ('modified_by_id', models.IntegerField(default=None)),
                ('e_status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='Active', max_length=10)),
                ('condo_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condos.condotype')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condos.location')),
            ],
        ),
    ]
