# Generated by Django 3.2.5 on 2021-08-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['group'],
            },
        ),
    ]
