# Generated by Django 3.2.5 on 2021-08-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condos',
            old_name='eStatus',
            new_name='e_status',
        ),
        migrations.RenameField(
            model_name='condos',
            old_name='Province',
            new_name='province',
        ),
    ]
