# Generated by Django 3.2.5 on 2021-08-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='groups',
            field=models.ManyToManyField(to='condos.Group'),
        ),
    ]
