# Generated by Django 3.2.5 on 2021-08-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0002_auto_20210820_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condos',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='condos.location'),
        ),
    ]
