# Generated by Django 3.2.5 on 2021-08-27 07:01

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('key', models.CharField(help_text='Refresh token', max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('expired', models.DateTimeField(default=authorization.models.set_refresh_token_time_expiration, help_text='Expired datetime')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
            },
        ),
    ]
